package com.jtj.exam.demo.vo;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Member {
	private int mem_id;
	private String mem_userid;
	private String mem_email;
	private String mem_password;
	private String mem_username;
	private String mem_nickname;
	private int mem_level;
	private int mem_point;
	private String mem_homepage;
	private String mem_phone;
	private String mem_birthday;
	private int mem_sex;
	private int mem_zipcode;
	private String mem_address1;
	private String mem_address2;
	private String mem_address3;
	private String mem_address4;
	private int mem_receive_email;
	private int mem_use_note;
	private int mem_receive_sms;
	private int mem_open_profile;
	private int mem_denied;
	private int mem_email_cert;
	private String mem_register_datetime;
	private String mem_register_ip;
	private String mem_lastlogin_datetime;
	private String mem_lastlogin_ip;
	private String mem_is_admin;
	private String mem_profile_content;
	private String mem_adminmemo;
	private int mem_following;
	private int mem_followed;
	private String mem_icon;
	private String mem_photo;
	private String updatedAt;
	private int unread;
	private String roadHourType;
	private String roadLocType;
	private String bankName;
	private String bankAccount;
	private String lastLoginToken;
	private int allowPushNoti;
	private String phoneNum;
	private String beaconStatus;
	private String beaconType;
	private String beaconSerial;
	private String vehicleType;
	private String vehicleSize;
	private String vehicleManufacturer;
	private String vehicleModelName;
	private int driverLicenseStatus;
	private String driverLicenseRejectReason;
	private String signupMethod;
	private int accEarning;
	private int bankAccountStatus;
	private String bankAccountRejectReason;
	private int vehicleRegStatus;
	private String vehicleRegRejectReason;
	private int joinId;
	private int reservedJoinId;
	private int numCampaignsTotal;
	private String deviceID;
	private int recPushSent;
	private String lastCampaignFinishedAt;
	private String beaconReturnPushSentAt;
	private String lastKnownLocation;
	private int lastExposureLevel;
	private String lastChargedAt;
	private int enableForceTestingMode;
	private String driverLicenseApprovedAt;
	private int promoPush11Hours;
	private int promoPush11Count;
	private int promoPush12Hours;
	private int promoPush12Count;
	private String deletedAt;
	private int pendingEarning;
	private int availableEarning;
	private int rewardedEarning;
	private int masterId;
	private String leftAt;
	private int advertiserId;
	private String invitationCode;
	private float danglePoint;
	private int dangleCash;
	private int campaignPoint;
	private int campaignCash;
	private String resCarModelType;
	private String resVehicleIdNo;
	private String resMotorType;
	private String resUseType;
	private String vehicleRegNo;
	private String vehicleOwnerName;
	private int isDriving;
	private int isBooster;
}
